// --- Day 7: Laboratories ---
// You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.
//
// Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.
//
// Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.
//
// Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.
//
// You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.
//
// For example:
//
// .......S.......
// ...............
// .......^.......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:
//
// .......S.......
// .......|.......
// .......^.......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// At that point, the original beam stops, and two new beams are emitted from the splitter:
//
// .......S.......
// .......|.......
// ......|^|......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// Those beams continue downward until they reach more splitters:
//
// .......S.......
// .......|.......
// ......|^|......
// ......|.|......
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:
//
// .......S.......
// .......|.......
// ......|^|......
// ......|.|......
// .....|^|^|.....
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// This process continues until all of the tachyon beams reach a splitter or exit the manifold:
//
// .......S.......
// .......|.......
// ......|^|......
// ......|.|......
// .....|^|^|.....
// .....|.|.|.....
// ....|^|^|^|....
// ....|.|.|.|....
// ...|^|^|||^|...
// ...|.|.|||.|...
// ..|^|^|||^|^|..
// ..|.|.|||.|.|..
// .|^|||^||.||^|.
// .|.|||.||.||.|.
// |^|^|^|^|^|||^|
// |.|.|.|.|.|||.|
// To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.
//
// Analyze your manifold diagram. How many times will the beam be split?
use std::fs;

fn main() {
    let input = load_input("input.txt");
    println!("Part 1: {}", solve_part1(&input));
    println!("Part 2: {}", solve_part2(&input));
}

fn load_input(input: &str) -> Vec<Vec<char>> {
    let graph = fs::read_to_string(input).expect("Failed to read input file");
    graph.lines().map(|line| line.chars().collect()).collect()
}

fn solve_part1(graph: &Vec<Vec<char>>) -> usize {
    let mut split_count = 0;
    let mut beam_positions = Vec::new();

    // Find the starting position of the beam (marked 'S')
    for (x, &cell) in graph[0].iter().enumerate() {
        if cell == 'S' {
            beam_positions.push(x);
            break;
        }
    }

    // Process each row of the graph
    for row in &graph[1..] {
        let mut new_beam_positions = Vec::new();
        let mut occupied_positions = std::collections::HashSet::new();

        for &pos in &beam_positions {
            if row[pos] == '^' {
                // Beam hits a splitter, create new beams to the left and right
                if pos > 0 {
                    new_beam_positions.push(pos - 1);
                    occupied_positions.insert(pos - 1);
                }
                if pos < row.len() - 1 {
                    new_beam_positions.push(pos + 1);
                    occupied_positions.insert(pos + 1);
                }
                split_count += 1;
            } else {
                // Beam continues downwards
                new_beam_positions.push(pos);
                occupied_positions.insert(pos);
            }
        }

        // Remove duplicates by converting to a set and back to a vector
        beam_positions = occupied_positions.into_iter().collect();
    }

    split_count
}

// --- Part Two ---
// With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.
//
// With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.
//
// Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.
//
// To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.
//
// In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:
//
// .......S.......
// .......|.......
// ......|^.......
// ......|........
// .....|^.^......
// .....|.........
// ....|^.^.^.....
// ....|..........
// ...|^.^...^....
// ...|...........
// ..|^.^...^.^...
// ..|............
// .|^...^.....^..
// .|.............
// |^.^.^.^.^...^.
// |..............
// Or, there's the timeline where the particle alternated going left and right at each splitter:
//
// .......S.......
// .......|.......
// ......|^.......
// ......|........
// ......^|^......
// .......|.......
// .....^|^.^.....
// ......|........
// ....^.^|..^....
// .......|.......
// ...^.^.|.^.^...
// .......|.......
// ..^...^|....^..
// .......|.......
// .^.^.^|^.^...^.
// ......|........
// Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:
//
// .......S.......
// .......|.......
// ......|^.......
// ......|........
// .....|^.^......
// .....|.........
// ....|^.^.^.....
// ....|..........
// ....^|^...^....
// .....|.........
// ...^.^|..^.^...
// ......|........
// ..^..|^.....^..
// .....|.........
// .^.^.^|^.^...^.
// ......|........
// In this example, in total, the particle ends up on 40 different timelines.
//
// Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?

fn solve_part2(graph: &Vec<Vec<char>>) -> usize {
    use std::collections::HashMap;
    
    // Map of column -> number of beams at that column
    let mut beams = HashMap::new();
    
    // Find the starting position and initialize with 1 beam
    for (x, &cell) in graph[0].iter().enumerate() {
        if cell == 'S' {
            beams.insert(x, 1);
            break;
        }
    }

    // Process each row
    for row in &graph[1..] {
        let mut new_beams = HashMap::new();

        for (x, &beam_cnt) in &beams {
            match row[*x] {
                '^' => {
                    // Splitter: split each beam into two (left and right)
                    if *x > 0 {
                        *new_beams.entry(*x - 1).or_insert(0) += beam_cnt;
                    }
                    if *x < row.len() - 1 {
                        *new_beams.entry(*x + 1).or_insert(0) += beam_cnt;
                    }
                }
                _ => {
                    // Empty space: beam continues straight
                    *new_beams.entry(*x).or_insert(0) += beam_cnt;
                }
            }
        }

        beams = new_beams;
    }

    // Sum all the beams that reached the bottom
    beams.values().sum()
}
